apiVersion: v1
kind: Service
metadata:
  name: {{ template "neo4j.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "neo4j.name" . }}
  annotations:
  {{- if .Values.service.annotations }}
  {{- include "neo4j.tplValue" (dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- include "neo4j.tplValue" (dict "value" .Values.service.loadBalancerSourceRanges "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
  selector:
    app: {{ template "neo4j.name" . }}
    release: {{ .Release.Name | quote }}